insert into public.episodes (
  title,
  "episodeRough",
  punchline,
  "episodeMain",
  note,
  status,
  category,
  tags,
  "talkLength",
  moods,
  "suitableScenes",
  "audienceTypes",
  "audienceSize",
  "audienceComedyLevel",
  "classificationReason",
  "aiPunchline",
  "aiScore",
  "aiReview"
)
values (
  'AI面接',
  'AI面接、的をいた質問をしなさすぎてキレる。30分後に落ちる',
  '最速の30分後に落選のメールが届いた',
  '就活の時に、ある企業の面接がAI面接だったんですよ。文字通り、人間の面接官じゃなくて画面に向かって喋ったら、AIが質問をしてくれるみたいな。',
  'もう少し短くしたほうがいいかな？',
  'COMPLETED',
  '就活',
  array['AI面接', '就活', '落選', 'コミュニケーション', '失敗談'],
  'MEDIUM',
  array['AWKWARD', 'ANGER', 'EMBARRASSING']::public.mood[],
  array['FRIENDS', 'CASUAL_CHAT']::public.scene[],
  array['CLOSE_FRIENDS', 'COMEDY_FANS']::public.audience_type[],
  'SMALL_GROUP',
  'NORMAL',
  'AI面接で質問が噛み合わなかったことと、30分後に落選通知が来たスピード感が面白さの中心。',
  '30分で落ちた最速の面接体験！',
  70,
  '具体的なシチュエーションは伝わりやすいが、少し短くするとオチが際立つ。'
);